def game_print(board):
    print("     |     |     ")
    print("  " + board[(0, 2)] + "  |  " + board[(1, 2)] + "  |  " + board[(2, 2)] + "  ")
    print("     |     |     ")
    print("-----|-----|-----")
    print("     |     |     ")
    print("  " + board[(0, 1)] + "  |  " + board[(1, 1)] + "  |  " + board[(2, 1)] + "  ")
    print("     |     |     ")
    print("-----|-----|-----")
    print("     |     |     ")
    print("  " + board[(0, 0)] + "  |  " + board[(1, 0)] + "  |  " + board[(2, 0)] + "  ")
    print("     |     |     ")

def game_init():
    print("     |     |     ")
    print("  " + "7" + "  |  " + "8" + "  |  " + "9" + "  ")
    print("     |     |     ")
    print("-----|-----|-----")
    print("     |     |     ")
    print("  " + "4" + "  |  " + "5" + "  |  " + "6" + "  ")
    print("     |     |     ")
    print("-----|-----|-----")
    print("     |     |     ")
    print("  " + "1" + "  |  " + "2" + "  |  " + "3" + "  ")
    print("     |     |     ")
